defaultPlacement: end
enableVersioning: true
entryTypes:
  - be8f3539-f760-4b83-a44f-c8a6e5188589 # Bill
handle: bill_section
maxAuthors: 1
name: Bills
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7d96a7b3-c138-4ef4-96f8-afb1d8b50a71: # my-craft-site
    enabledByDefault: true
    hasUrls: true
    template: stock/_entry.twig
    uriFormat: 'stock/{slug}'
type: channel
