altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9a5844bc-258e-4f3d-a85c-7b8945a0667e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-28T19:08:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 960b4e28-1a54-4f61-a324-b2bea8e90125
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-12-28T19:16:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 14a6460a-6fb0-4204-b0ad-a4d53a3cc0bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1288b310-db6f-4575-9730-9141571e133e
        userCondition: null
fs: img
handle: images
name: images
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: img
transformSubpath: ''
