color: red
fieldLayouts:
  b0238a05-6781-4458-b7fa-a25585bfda58:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-30T23:28:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3910ab16-3b4f-4c03-be76-f29917c18efe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T23:31:01+00:00'
            elementCondition: null
            fieldUid: 3afce2cf-32b2-470d-9738-d43d048391af # Drink
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d8e689d-113b-40a4-9a7f-e192259cf12f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-02T15:23:28+00:00'
            elementCondition: null
            fieldUid: ce6f42af-5817-49ad-af9f-e0d1c76ebb86 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32bfd5e2-c3e0-4c2f-87ca-75d726585035
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T23:32:18+00:00'
            elementCondition: null
            fieldUid: 7d6462ff-0724-4fc0-bde1-222dd1b0ef21 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baa439b4-5a68-496d-9e48-626aaf67034e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T23:32:18+00:00'
            elementCondition: null
            fieldUid: 1f405637-aeb8-4555-80dc-13d06977fa08 # Amount
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c582e036-579c-41f0-b652-4c458eea8505
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5629c470-591f-45e7-9e9b-2771dd39db81
        userCondition: null
handle: bill_items
hasTitleField: true
icon: angle-right
name: 'Bill Items'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{bill_status}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
