color: null
fieldLayouts:
  e0c24db1-446c-4006-8f3f-b5ced4aa8ff8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-10T02:04:46+00:00'
            elementCondition: null
            fieldUid: 1ae6ffbd-db4f-4e1d-832f-d47abbad3215 # User
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90bd7512-074a-472f-8ae6-b07d690eef50
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T02:04:46+00:00'
            elementCondition: null
            fieldUid: b8fc6760-c00c-429f-b7fc-9f871eae7f2c
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 652a6abe-64be-4050-83e0-74f8926f07bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T02:04:46+00:00'
            elementCondition: null
            fieldUid: e72337c8-801c-44a4-a270-389bf9e9672c
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fcd5185-a9ea-4c84-b54a-9788fe7f5be4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1a63e7b-0d79-46c0-a77b-e0a5374a004b
        userCondition: null
handle: cantplay
hasTitleField: false
icon: null
name: Cantplay
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{p_user[0].fullname} - {p_cantplay} - {p_selected}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
