color: null
fieldLayouts:
  0109cdc5-8299-49a4-ab9b-eabf89096738:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-10T01:58:59+00:00'
            elementCondition: null
            fieldUid: 1ae6ffbd-db4f-4e1d-832f-d47abbad3215 # User
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e247ded7-7ef7-4bd2-9857-04d1d977e73f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T01:58:59+00:00'
            elementCondition: null
            fieldUid: d7c3cb9e-d5d0-4469-97f7-f40fb7e4b389
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adcf2147-32a5-40cf-a01a-3872839aea58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T01:58:59+00:00'
            elementCondition: null
            fieldUid: e72337c8-801c-44a4-a270-389bf9e9672c
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec42e703-7ca1-4974-867a-bd9e416cb7bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b4ef528-af19-439f-8e71-9681a4903c4c
        userCondition: null
handle: canyouplay
hasTitleField: false
icon: null
name: Canyouplay
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{p_user[0].fullName} - {p_canplaystatus} - {p_selected}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
