color: null
fieldLayouts:
  f6121032-bf1d-437f-bb05-4487e4e5d1fa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-07T16:57:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Team A'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1de12eb9-3d6b-4941-b47c-c1679b6d2eee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T17:00:05+00:00'
            elementCondition: null
            fieldUid: 59d9a8b7-80b8-465a-9855-1ebbb8adeed2 # Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eaeb6e98-9128-4150-bfd1-b444c90b5c56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T17:00:05+00:00'
            elementCondition: null
            fieldUid: 8af941d5-aecb-4469-9392-3bea877dbbce # date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d2fd836-d2e7-45cc-bac7-c9e0e9b6736d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-11T20:08:21+00:00'
            elementCondition: null
            fieldUid: b757ee0c-8df3-424f-9280-cba3fa503a9a # Participants
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74fec5e7-f1a9-4509-aa23-cee6dd7b62a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8344f814-fff3-4311-b8b7-539d62badb45
        userCondition: null
handle: teama
hasTitleField: true
icon: null
name: TeamA
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
