color: rose
fieldLayouts:
  10254eb1-09f6-4ed0-a342-c829857e3b73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-07T16:59:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Team B'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1b19938f-4cfb-4a27-a259-2c5cc08e5164
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T17:00:25+00:00'
            elementCondition: null
            fieldUid: 59d9a8b7-80b8-465a-9855-1ebbb8adeed2 # Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 007ed848-ed1a-4230-89a5-f0bf0d20ff06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T17:00:25+00:00'
            elementCondition: null
            fieldUid: 8af941d5-aecb-4469-9392-3bea877dbbce # date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66b08525-7a72-49e0-811a-fe856e93a227
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-11T21:44:12+00:00'
            elementCondition: null
            fieldUid: b757ee0c-8df3-424f-9280-cba3fa503a9a # Participants
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03025bb3-e68c-4ebd-b438-ccffdfe1f04c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1acdfaf-3750-490b-8465-2037d082caf0
        userCondition: null
handle: teamb
hasTitleField: true
icon: null
name: TeamB
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
