columnSuffix: null
handle: bill_status
instructions: null
name: 'Bill Status'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Open
        -
          - value
          - open
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Paid
        -
          - value
          - paid
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
