columnSuffix: null
handle: bill_items
instructions: null
name: 'Bill Items'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - 0b8f4b52-973b-4a0a-a7af-4b68d0e1a6e5 # Bill Items
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
