columnSuffix: null
handle: p_status
instructions: null
name: Status
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Selected
        -
          - value
          - selected
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Reserve
        -
          - value
          - reserve
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Not selected'
        -
          - value
          - notSelected
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pending
        -
          - value
          - pending
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
