columnSuffix: null
handle: reserve
instructions: null
name: Reserve
searchable: false
settings:
  createButtonLabel: 'Add a player who can play as a "reserve"'
  defaultIndexViewMode: cards
  entryTypes:
    - c294ce45-3bcf-4331-8a2b-11c488140b25 # Reserve
  includeTableView: false
  maxEntries: 2
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
